This notebook is to prep for my interview with an undisclosed company in Adtech
- Date: June 19th, 2026

# Prep
## Imports

In [6]:
## if running into errors with pip, add to PATH
# import sys, os
# print(os.path.dirname(sys.executable))

In [7]:
!pip install -r ../requirements.txt
# !python -m pip freeze > requirements.txt

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import sklearn
import seaborn as sns
import scipy
# import scikit-learn

## Constants

In [9]:
DATA_PATH = "../data/"

## Load in Data

In [10]:
campaign_df = pd.read_csv(DATA_PATH + "campaign_performance.csv")
print(campaign_df.shape[0])
campaign_df.head(3)

4288

,date,campaign_id,campaign_name,channel,region,weather_severity_index,impressions,clicks,spend_cad,conversions,revenue_cad,cpm_cad,cpc_cad,roas
0,2025-12-22,CMP1002,Premium_Upgrade_Q1,Connected TV,Quebec,0.871,48337,951.5,702.84,22.10,1481.14,14.54,0.739,2.107
1,2025-11-29,CMP1004,Brand_Lift_National,Connected TV,Quebec,0.374,36764,539.9,248.47,25.07,1746.93,6.76,0.460,7.031
2,2025-12-11,CMP1006,Spring_Forecast_Launch,Display,British Columbia,0.982,83195,1353.7,759.46,56.94,2276.05,9.13,0.561,2.997

In [11]:
users_df = pd.read_csv(DATA_PATH + "users.csv")
print(users_df.shape[0])
users_df.head(3)

3010

,user_id,signup_date,acquisition_channel,region,plan_type,avg_monthly_sessions,alerts_enabled,push_notifications_enabled,tenure_months,churned,churn_date,ltv_cad
0,U100452,2024-12-10,Native,Atlantic,Free,0.85,1,0,12.90,0,NaN,0.0
1,U101657,2025-11-24,Referral,Ontario,Free,5.90,1,1,1.27,0,NaN,0.0
2,U100062,2024-12-03,Organic,Ontario,Premium,0.27,0,0,13.13,0,NaN,304.5

In [12]:
adtech_df = pd.read_excel(DATA_PATH + "adtech_practice_dataset.xlsx")
print(adtech_df.shape[0])
adtech_df.head(3)

4288

,date,campaign_id,campaign_name,channel,region,weather_severity_index,impressions,clicks,spend_cad,conversions,revenue_cad,cpm_cad,cpc_cad,roas
0,2025-12-22,CMP1002,Premium_Upgrade_Q1,Connected TV,Quebec,0.871,48337,951.5,702.84,22.10,1481.14,14.54,0.739,2.107
1,2025-11-29,CMP1004,Brand_Lift_National,Connected TV,Quebec,0.374,36764,539.9,248.47,25.07,1746.93,6.76,0.460,7.031
2,2025-12-11,CMP1006,Spring_Forecast_Launch,Display,British Columbia,0.982,83195,1353.7,759.46,56.94,2276.05,9.13,0.561,2.997